// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gateway "github.com/DanielPopoola/fairqueue/internal/gateway"
	mock "github.com/stretchr/testify/mock"
)

// PaymentGateway is an autogenerated mock type for the PaymentGateway type
type PaymentGateway struct {
	mock.Mock
}

// InitializeTransaction provides a mock function with given fields: ctx, req
func (_m *PaymentGateway) InitializeTransaction(ctx context.Context, req gateway.InitializeRequest) (*gateway.InitializeResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InitializeTransaction")
	}

	var r0 *gateway.InitializeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gateway.InitializeRequest) (*gateway.InitializeResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gateway.InitializeRequest) *gateway.InitializeResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.InitializeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gateway.InitializeRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyTransaction provides a mock function with given fields: ctx, reference
func (_m *PaymentGateway) VerifyTransaction(ctx context.Context, reference string) (*gateway.VerifyResponse, error) {
	ret := _m.Called(ctx, reference)

	if len(ret) == 0 {
		panic("no return value specified for VerifyTransaction")
	}

	var r0 *gateway.VerifyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gateway.VerifyResponse, error)); ok {
		return rf(ctx, reference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gateway.VerifyResponse); ok {
		r0 = rf(ctx, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.VerifyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyWebhookSignature provides a mock function with given fields: payload, signature
func (_m *PaymentGateway) VerifyWebhookSignature(payload []byte, signature string) bool {
	ret := _m.Called(payload, signature)

	if len(ret) == 0 {
		panic("no return value specified for VerifyWebhookSignature")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func([]byte, string) bool); ok {
		r0 = rf(payload, signature)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewPaymentGateway creates a new instance of PaymentGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentGateway {
	mock := &PaymentGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
