// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CustomerAuthScopes  = "CustomerAuth.Scopes"
	OrganizerAuthScopes = "OrganizerAuth.Scopes"
)

// Defines values for ErrorResponseErrorCode.
const (
	ADMISSIONTOKENEXPIRED ErrorResponseErrorCode = "ADMISSION_TOKEN_EXPIRED"
	ALREADYCLAIMED        ErrorResponseErrorCode = "ALREADY_CLAIMED"
	ALREADYINQUEUE        ErrorResponseErrorCode = "ALREADY_IN_QUEUE"
	CLAIMEXPIRED          ErrorResponseErrorCode = "CLAIM_EXPIRED"
	EVENTNOTACTIVE        ErrorResponseErrorCode = "EVENT_NOT_ACTIVE"
	EVENTSOLDOUT          ErrorResponseErrorCode = "EVENT_SOLD_OUT"
	FORBIDDEN             ErrorResponseErrorCode = "FORBIDDEN"
	INTERNALERROR         ErrorResponseErrorCode = "INTERNAL_ERROR"
	INVALIDCREDENTIALS    ErrorResponseErrorCode = "INVALID_CREDENTIALS"
	INVALIDOTP            ErrorResponseErrorCode = "INVALID_OTP"
	INVALIDTRANSITION     ErrorResponseErrorCode = "INVALID_TRANSITION"
	NOTFOUND              ErrorResponseErrorCode = "NOT_FOUND"
	UNAUTHORIZED          ErrorResponseErrorCode = "UNAUTHORIZED"
)

// Defines values for EventStatus.
const (
	ACTIVE  EventStatus = "ACTIVE"
	DRAFT   EventStatus = "DRAFT"
	ENDED   EventStatus = "ENDED"
	SOLDOUT EventStatus = "SOLD_OUT"
)

// Defines values for HealthResponsePostgres.
const (
	HealthResponsePostgresError HealthResponsePostgres = "error"
	HealthResponsePostgresOk    HealthResponsePostgres = "ok"
)

// Defines values for HealthResponseRedis.
const (
	HealthResponseRedisError HealthResponseRedis = "error"
	HealthResponseRedisOk    HealthResponseRedis = "ok"
)

// Defines values for HealthResponseStatus.
const (
	Degraded  HealthResponseStatus = "degraded"
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for PaystackWebhookPayloadEvent.
const (
	ChargeFailed  PaystackWebhookPayloadEvent = "charge.failed"
	ChargeSuccess PaystackWebhookPayloadEvent = "charge.success"
)

// Defines values for QueuePositionResponseDataStatus.
const (
	ADMITTED QueuePositionResponseDataStatus = "ADMITTED"
	WAITING  QueuePositionResponseDataStatus = "WAITING"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Data *struct {
		OrganizerId *openapi_types.UUID `json:"organizer_id,omitempty"`
		Token       *string             `json:"token,omitempty"`
	} `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// ClaimRequest defines model for ClaimRequest.
type ClaimRequest struct {
	// AdmissionToken Short-lived token issued by the admission worker
	AdmissionToken string `json:"admission_token"`
}

// ClaimResponse defines model for ClaimResponse.
type ClaimResponse struct {
	Data *struct {
		ClaimId *openapi_types.UUID `json:"claim_id,omitempty"`
		EventId *openapi_types.UUID `json:"event_id,omitempty"`

		// ExpiresAt When the claim expires if payment is not completed
		ExpiresAt *time.Time `json:"expires_at,omitempty"`
	} `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// CreateEventRequest defines model for CreateEventRequest.
type CreateEventRequest struct {
	Name string `json:"name"`

	// Price Ticket price in NGN.
	Price          int64     `json:"price"`
	SaleEnd        time.Time `json:"sale_end"`
	SaleStart      time.Time `json:"sale_start"`
	TotalInventory int       `json:"total_inventory"`
}

// CustomerAuthResponse defines model for CustomerAuthResponse.
type CustomerAuthResponse struct {
	Data *struct {
		CustomerId *openapi_types.UUID `json:"customer_id,omitempty"`
		Token      *string             `json:"token,omitempty"`
	} `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *struct {
		// Code Machine-readable error code matching domain errors
		Code ErrorResponseErrorCode `json:"code"`

		// Message Human-readable description
		Message string `json:"message"`
	} `json:"error,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// ErrorResponseErrorCode Machine-readable error code matching domain errors
type ErrorResponseErrorCode string

// Event defines model for Event.
type Event struct {
	CreatedAt      *time.Time          `json:"created_at,omitempty"`
	Id             *openapi_types.UUID `json:"id,omitempty"`
	Name           *string             `json:"name,omitempty"`
	OrganizerId    *openapi_types.UUID `json:"organizer_id,omitempty"`
	Price          *int64              `json:"price,omitempty"`
	SaleEnd        *time.Time          `json:"sale_end,omitempty"`
	SaleStart      *time.Time          `json:"sale_start,omitempty"`
	Status         *EventStatus        `json:"status,omitempty"`
	TotalInventory *int                `json:"total_inventory,omitempty"`
	UpdatedAt      *time.Time          `json:"updated_at,omitempty"`
}

// EventStatus defines model for Event.Status.
type EventStatus string

// EventResponse defines model for EventResponse.
type EventResponse struct {
	Data    *Event `json:"data,omitempty"`
	Success *bool  `json:"success,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Postgres *HealthResponsePostgres `json:"postgres,omitempty"`
	Redis    *HealthResponseRedis    `json:"redis,omitempty"`
	Status   *HealthResponseStatus   `json:"status,omitempty"`
}

// HealthResponsePostgres defines model for HealthResponse.Postgres.
type HealthResponsePostgres string

// HealthResponseRedis defines model for HealthResponse.Redis.
type HealthResponseRedis string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// OTPRequestBody defines model for OTPRequestBody.
type OTPRequestBody struct {
	Email openapi_types.Email `json:"email"`
}

// OTPVerifyRequest defines model for OTPVerifyRequest.
type OTPVerifyRequest struct {
	Email openapi_types.Email `json:"email"`
	Otp   string              `json:"otp"`
}

// OrganizerLoginRequest defines model for OrganizerLoginRequest.
type OrganizerLoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PaymentInitResponse defines model for PaymentInitResponse.
type PaymentInitResponse struct {
	Data *struct {
		// AuthorizationUrl Paystack-hosted checkout URL
		AuthorizationUrl *string             `json:"authorization_url,omitempty"`
		PaymentId        *openapi_types.UUID `json:"payment_id,omitempty"`

		// Reference Payment reference for reconciliation
		Reference *string `json:"reference,omitempty"`
	} `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// PaystackWebhookPayload defines model for PaystackWebhookPayload.
type PaystackWebhookPayload struct {
	Data struct {
		GatewayResponse *string `json:"gateway_response,omitempty"`
		Reference       *string `json:"reference,omitempty"`
		Status          *string `json:"status,omitempty"`
	} `json:"data"`
	Event PaystackWebhookPayloadEvent `json:"event"`
}

// PaystackWebhookPayloadEvent defines model for PaystackWebhookPayload.Event.
type PaystackWebhookPayloadEvent string

// QueueJoinResponse defines model for QueueJoinResponse.
type QueueJoinResponse struct {
	Data *struct {
		EventId *openapi_types.UUID `json:"event_id,omitempty"`

		// Position 1-based position in the waiting queue
		Position     *int                `json:"position,omitempty"`
		QueueEntryId *openapi_types.UUID `json:"queue_entry_id,omitempty"`
	} `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// QueuePositionResponse defines model for QueuePositionResponse.
type QueuePositionResponse struct {
	Data *struct {
		// AdmissionToken Present only when status is ADMITTED
		AdmissionToken *string `json:"admission_token"`

		// Position Current 1-based position. 0 means admitted.
		Position *int                             `json:"position,omitempty"`
		Status   *QueuePositionResponseDataStatus `json:"status,omitempty"`
	} `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// QueuePositionResponseDataStatus defines model for QueuePositionResponse.Data.Status.
type QueuePositionResponseDataStatus string

// ClaimId defines model for ClaimId.
type ClaimId = openapi_types.UUID

// EventId defines model for EventId.
type EventId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// PaystackWebhookParams defines parameters for PaystackWebhook.
type PaystackWebhookParams struct {
	// XPaystackSignature HMAC-SHA512 signature of the request body using the Paystack secret key
	XPaystackSignature string `json:"x-paystack-signature"`
}

// QueueWebSocketParams defines parameters for QueueWebSocket.
type QueueWebSocketParams struct {
	// Token Customer JWT (required because browser WebSocket API cannot set Authorization header)
	Token string `form:"token" json:"token"`
}

// RequestOTPJSONRequestBody defines body for RequestOTP for application/json ContentType.
type RequestOTPJSONRequestBody = OTPRequestBody

// VerifyOTPJSONRequestBody defines body for VerifyOTP for application/json ContentType.
type VerifyOTPJSONRequestBody = OTPVerifyRequest

// OrganizerLoginJSONRequestBody defines body for OrganizerLogin for application/json ContentType.
type OrganizerLoginJSONRequestBody = OrganizerLoginRequest

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = CreateEventRequest

// ClaimTicketJSONRequestBody defines body for ClaimTicket for application/json ContentType.
type ClaimTicketJSONRequestBody = ClaimRequest

// PaystackWebhookJSONRequestBody defines body for PaystackWebhook for application/json ContentType.
type PaystackWebhookJSONRequestBody = PaystackWebhookPayload

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Request OTP
	// (POST /auth/customer/otp/request)
	RequestOTP(w http.ResponseWriter, r *http.Request)
	// Verify OTP
	// (POST /auth/customer/otp/verify)
	VerifyOTP(w http.ResponseWriter, r *http.Request)
	// Organizer login
	// (POST /auth/organizer/login)
	OrganizerLogin(w http.ResponseWriter, r *http.Request)
	// Release a claim
	// (DELETE /claims/{claimId})
	ReleaseClaim(w http.ResponseWriter, r *http.Request, claimId ClaimId)
	// Initialize payment
	// (POST /claims/{claimId}/payments)
	InitializePayment(w http.ResponseWriter, r *http.Request, claimId ClaimId)
	// Create event
	// (POST /events)
	CreateEvent(w http.ResponseWriter, r *http.Request)
	// Get event
	// (GET /events/{eventId})
	GetEvent(w http.ResponseWriter, r *http.Request, eventId EventId)
	// Activate event
	// (PUT /events/{eventId}/activate)
	ActivateEvent(w http.ResponseWriter, r *http.Request, eventId EventId)
	// Claim a ticket
	// (POST /events/{eventId}/claims)
	ClaimTicket(w http.ResponseWriter, r *http.Request, eventId EventId)
	// End event
	// (PUT /events/{eventId}/end)
	EndEvent(w http.ResponseWriter, r *http.Request, eventId EventId)
	// Abandon queue
	// (DELETE /events/{eventId}/queue)
	AbandonQueue(w http.ResponseWriter, r *http.Request, eventId EventId)
	// Join queue
	// (POST /events/{eventId}/queue)
	JoinQueue(w http.ResponseWriter, r *http.Request, eventId EventId)
	// Get queue position
	// (GET /events/{eventId}/queue/position)
	GetQueuePosition(w http.ResponseWriter, r *http.Request, eventId EventId)
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// Paystack webhook
	// (POST /webhooks/paystack)
	PaystackWebhook(w http.ResponseWriter, r *http.Request, params PaystackWebhookParams)
	// Queue position WebSocket
	// (GET /ws/queue/{eventId})
	QueueWebSocket(w http.ResponseWriter, r *http.Request, eventId EventId, params QueueWebSocketParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Request OTP
// (POST /auth/customer/otp/request)
func (_ Unimplemented) RequestOTP(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify OTP
// (POST /auth/customer/otp/verify)
func (_ Unimplemented) VerifyOTP(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Organizer login
// (POST /auth/organizer/login)
func (_ Unimplemented) OrganizerLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Release a claim
// (DELETE /claims/{claimId})
func (_ Unimplemented) ReleaseClaim(w http.ResponseWriter, r *http.Request, claimId ClaimId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Initialize payment
// (POST /claims/{claimId}/payments)
func (_ Unimplemented) InitializePayment(w http.ResponseWriter, r *http.Request, claimId ClaimId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create event
// (POST /events)
func (_ Unimplemented) CreateEvent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get event
// (GET /events/{eventId})
func (_ Unimplemented) GetEvent(w http.ResponseWriter, r *http.Request, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Activate event
// (PUT /events/{eventId}/activate)
func (_ Unimplemented) ActivateEvent(w http.ResponseWriter, r *http.Request, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Claim a ticket
// (POST /events/{eventId}/claims)
func (_ Unimplemented) ClaimTicket(w http.ResponseWriter, r *http.Request, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// End event
// (PUT /events/{eventId}/end)
func (_ Unimplemented) EndEvent(w http.ResponseWriter, r *http.Request, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Abandon queue
// (DELETE /events/{eventId}/queue)
func (_ Unimplemented) AbandonQueue(w http.ResponseWriter, r *http.Request, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Join queue
// (POST /events/{eventId}/queue)
func (_ Unimplemented) JoinQueue(w http.ResponseWriter, r *http.Request, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get queue position
// (GET /events/{eventId}/queue/position)
func (_ Unimplemented) GetQueuePosition(w http.ResponseWriter, r *http.Request, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Paystack webhook
// (POST /webhooks/paystack)
func (_ Unimplemented) PaystackWebhook(w http.ResponseWriter, r *http.Request, params PaystackWebhookParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Queue position WebSocket
// (GET /ws/queue/{eventId})
func (_ Unimplemented) QueueWebSocket(w http.ResponseWriter, r *http.Request, eventId EventId, params QueueWebSocketParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RequestOTP operation middleware
func (siw *ServerInterfaceWrapper) RequestOTP(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestOTP(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyOTP operation middleware
func (siw *ServerInterfaceWrapper) VerifyOTP(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyOTP(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OrganizerLogin operation middleware
func (siw *ServerInterfaceWrapper) OrganizerLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OrganizerLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReleaseClaim operation middleware
func (siw *ServerInterfaceWrapper) ReleaseClaim(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "claimId" -------------
	var claimId ClaimId

	err = runtime.BindStyledParameterWithOptions("simple", "claimId", chi.URLParam(r, "claimId"), &claimId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "claimId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CustomerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReleaseClaim(w, r, claimId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InitializePayment operation middleware
func (siw *ServerInterfaceWrapper) InitializePayment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "claimId" -------------
	var claimId ClaimId

	err = runtime.BindStyledParameterWithOptions("simple", "claimId", chi.URLParam(r, "claimId"), &claimId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "claimId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CustomerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InitializePayment(w, r, claimId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OrganizerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ActivateEvent operation middleware
func (siw *ServerInterfaceWrapper) ActivateEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, OrganizerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ActivateEvent(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClaimTicket operation middleware
func (siw *ServerInterfaceWrapper) ClaimTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CustomerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClaimTicket(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EndEvent operation middleware
func (siw *ServerInterfaceWrapper) EndEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, OrganizerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EndEvent(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AbandonQueue operation middleware
func (siw *ServerInterfaceWrapper) AbandonQueue(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CustomerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AbandonQueue(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinQueue operation middleware
func (siw *ServerInterfaceWrapper) JoinQueue(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CustomerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinQueue(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQueuePosition operation middleware
func (siw *ServerInterfaceWrapper) GetQueuePosition(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CustomerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQueuePosition(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PaystackWebhook operation middleware
func (siw *ServerInterfaceWrapper) PaystackWebhook(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PaystackWebhookParams

	headers := r.Header

	// ------------- Required header parameter "x-paystack-signature" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-paystack-signature")]; found {
		var XPaystackSignature string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-paystack-signature", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-paystack-signature", valueList[0], &XPaystackSignature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-paystack-signature", Err: err})
			return
		}

		params.XPaystackSignature = XPaystackSignature

	} else {
		err := fmt.Errorf("Header parameter x-paystack-signature is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-paystack-signature", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PaystackWebhook(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueueWebSocket operation middleware
func (siw *ServerInterfaceWrapper) QueueWebSocket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params QueueWebSocketParams

	// ------------- Required query parameter "token" -------------

	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "token", r.URL.Query(), &params.Token)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueueWebSocket(w, r, eventId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/customer/otp/request", wrapper.RequestOTP)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/customer/otp/verify", wrapper.VerifyOTP)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/organizer/login", wrapper.OrganizerLogin)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/claims/{claimId}", wrapper.ReleaseClaim)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/claims/{claimId}/payments", wrapper.InitializePayment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events", wrapper.CreateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/{eventId}", wrapper.GetEvent)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/events/{eventId}/activate", wrapper.ActivateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events/{eventId}/claims", wrapper.ClaimTicket)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/events/{eventId}/end", wrapper.EndEvent)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/events/{eventId}/queue", wrapper.AbandonQueue)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/events/{eventId}/queue", wrapper.JoinQueue)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events/{eventId}/queue/position", wrapper.GetQueuePosition)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/webhooks/paystack", wrapper.PaystackWebhook)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ws/queue/{eventId}", wrapper.QueueWebSocket)
	})

	return r
}

type BadRequestJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type RequestOTPRequestObject struct {
	Body *RequestOTPJSONRequestBody
}

type RequestOTPResponseObject interface {
	VisitRequestOTPResponse(w http.ResponseWriter) error
}

type RequestOTP200JSONResponse MessageResponse

func (response RequestOTP200JSONResponse) VisitRequestOTPResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RequestOTP429JSONResponse ErrorResponse

func (response RequestOTP429JSONResponse) VisitRequestOTPResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type RequestOTP500JSONResponse struct{ InternalErrorJSONResponse }

func (response RequestOTP500JSONResponse) VisitRequestOTPResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type VerifyOTPRequestObject struct {
	Body *VerifyOTPJSONRequestBody
}

type VerifyOTPResponseObject interface {
	VisitVerifyOTPResponse(w http.ResponseWriter) error
}

type VerifyOTP200JSONResponse CustomerAuthResponse

func (response VerifyOTP200JSONResponse) VisitVerifyOTPResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type VerifyOTP401JSONResponse ErrorResponse

func (response VerifyOTP401JSONResponse) VisitVerifyOTPResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type VerifyOTP500JSONResponse struct{ InternalErrorJSONResponse }

func (response VerifyOTP500JSONResponse) VisitVerifyOTPResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type OrganizerLoginRequestObject struct {
	Body *OrganizerLoginJSONRequestBody
}

type OrganizerLoginResponseObject interface {
	VisitOrganizerLoginResponse(w http.ResponseWriter) error
}

type OrganizerLogin200JSONResponse AuthResponse

func (response OrganizerLogin200JSONResponse) VisitOrganizerLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type OrganizerLogin401JSONResponse ErrorResponse

func (response OrganizerLogin401JSONResponse) VisitOrganizerLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type OrganizerLogin500JSONResponse struct{ InternalErrorJSONResponse }

func (response OrganizerLogin500JSONResponse) VisitOrganizerLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ReleaseClaimRequestObject struct {
	ClaimId ClaimId `json:"claimId"`
}

type ReleaseClaimResponseObject interface {
	VisitReleaseClaimResponse(w http.ResponseWriter) error
}

type ReleaseClaim204Response struct {
}

func (response ReleaseClaim204Response) VisitReleaseClaimResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ReleaseClaim401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ReleaseClaim401JSONResponse) VisitReleaseClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ReleaseClaim403JSONResponse struct{ ForbiddenJSONResponse }

func (response ReleaseClaim403JSONResponse) VisitReleaseClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ReleaseClaim404JSONResponse struct{ NotFoundJSONResponse }

func (response ReleaseClaim404JSONResponse) VisitReleaseClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ReleaseClaim409JSONResponse ErrorResponse

func (response ReleaseClaim409JSONResponse) VisitReleaseClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ReleaseClaim500JSONResponse struct{ InternalErrorJSONResponse }

func (response ReleaseClaim500JSONResponse) VisitReleaseClaimResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type InitializePaymentRequestObject struct {
	ClaimId ClaimId `json:"claimId"`
}

type InitializePaymentResponseObject interface {
	VisitInitializePaymentResponse(w http.ResponseWriter) error
}

type InitializePayment201JSONResponse PaymentInitResponse

func (response InitializePayment201JSONResponse) VisitInitializePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type InitializePayment400JSONResponse ErrorResponse

func (response InitializePayment400JSONResponse) VisitInitializePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InitializePayment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response InitializePayment401JSONResponse) VisitInitializePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type InitializePayment403JSONResponse struct{ ForbiddenJSONResponse }

func (response InitializePayment403JSONResponse) VisitInitializePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type InitializePayment404JSONResponse struct{ NotFoundJSONResponse }

func (response InitializePayment404JSONResponse) VisitInitializePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type InitializePayment500JSONResponse struct{ InternalErrorJSONResponse }

func (response InitializePayment500JSONResponse) VisitInitializePaymentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateEventRequestObject struct {
	Body *CreateEventJSONRequestBody
}

type CreateEventResponseObject interface {
	VisitCreateEventResponse(w http.ResponseWriter) error
}

type CreateEvent201JSONResponse EventResponse

func (response CreateEvent201JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateEvent400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateEvent400JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateEvent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateEvent401JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateEvent500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateEvent500JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetEventRequestObject struct {
	EventId EventId `json:"eventId"`
}

type GetEventResponseObject interface {
	VisitGetEventResponse(w http.ResponseWriter) error
}

type GetEvent200JSONResponse EventResponse

func (response GetEvent200JSONResponse) VisitGetEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEvent404JSONResponse struct{ NotFoundJSONResponse }

func (response GetEvent404JSONResponse) VisitGetEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetEvent500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetEvent500JSONResponse) VisitGetEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ActivateEventRequestObject struct {
	EventId EventId `json:"eventId"`
}

type ActivateEventResponseObject interface {
	VisitActivateEventResponse(w http.ResponseWriter) error
}

type ActivateEvent200JSONResponse EventResponse

func (response ActivateEvent200JSONResponse) VisitActivateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ActivateEvent400JSONResponse ErrorResponse

func (response ActivateEvent400JSONResponse) VisitActivateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ActivateEvent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ActivateEvent401JSONResponse) VisitActivateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ActivateEvent403JSONResponse struct{ ForbiddenJSONResponse }

func (response ActivateEvent403JSONResponse) VisitActivateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ActivateEvent404JSONResponse struct{ NotFoundJSONResponse }

func (response ActivateEvent404JSONResponse) VisitActivateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ActivateEvent500JSONResponse struct{ InternalErrorJSONResponse }

func (response ActivateEvent500JSONResponse) VisitActivateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ClaimTicketRequestObject struct {
	EventId EventId `json:"eventId"`
	Body    *ClaimTicketJSONRequestBody
}

type ClaimTicketResponseObject interface {
	VisitClaimTicketResponse(w http.ResponseWriter) error
}

type ClaimTicket201JSONResponse ClaimResponse

func (response ClaimTicket201JSONResponse) VisitClaimTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type ClaimTicket400JSONResponse ErrorResponse

func (response ClaimTicket400JSONResponse) VisitClaimTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ClaimTicket401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ClaimTicket401JSONResponse) VisitClaimTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ClaimTicket409JSONResponse ErrorResponse

func (response ClaimTicket409JSONResponse) VisitClaimTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ClaimTicket410JSONResponse ErrorResponse

func (response ClaimTicket410JSONResponse) VisitClaimTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)

	return json.NewEncoder(w).Encode(response)
}

type ClaimTicket500JSONResponse struct{ InternalErrorJSONResponse }

func (response ClaimTicket500JSONResponse) VisitClaimTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type EndEventRequestObject struct {
	EventId EventId `json:"eventId"`
}

type EndEventResponseObject interface {
	VisitEndEventResponse(w http.ResponseWriter) error
}

type EndEvent200JSONResponse EventResponse

func (response EndEvent200JSONResponse) VisitEndEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type EndEvent400JSONResponse struct{ BadRequestJSONResponse }

func (response EndEvent400JSONResponse) VisitEndEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type EndEvent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response EndEvent401JSONResponse) VisitEndEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type EndEvent403JSONResponse struct{ ForbiddenJSONResponse }

func (response EndEvent403JSONResponse) VisitEndEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type EndEvent404JSONResponse struct{ NotFoundJSONResponse }

func (response EndEvent404JSONResponse) VisitEndEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type EndEvent500JSONResponse struct{ InternalErrorJSONResponse }

func (response EndEvent500JSONResponse) VisitEndEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AbandonQueueRequestObject struct {
	EventId EventId `json:"eventId"`
}

type AbandonQueueResponseObject interface {
	VisitAbandonQueueResponse(w http.ResponseWriter) error
}

type AbandonQueue204Response struct {
}

func (response AbandonQueue204Response) VisitAbandonQueueResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AbandonQueue400JSONResponse ErrorResponse

func (response AbandonQueue400JSONResponse) VisitAbandonQueueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AbandonQueue401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AbandonQueue401JSONResponse) VisitAbandonQueueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AbandonQueue404JSONResponse struct{ NotFoundJSONResponse }

func (response AbandonQueue404JSONResponse) VisitAbandonQueueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AbandonQueue500JSONResponse struct{ InternalErrorJSONResponse }

func (response AbandonQueue500JSONResponse) VisitAbandonQueueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type JoinQueueRequestObject struct {
	EventId EventId `json:"eventId"`
}

type JoinQueueResponseObject interface {
	VisitJoinQueueResponse(w http.ResponseWriter) error
}

type JoinQueue201JSONResponse QueueJoinResponse

func (response JoinQueue201JSONResponse) VisitJoinQueueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type JoinQueue400JSONResponse struct{ BadRequestJSONResponse }

func (response JoinQueue400JSONResponse) VisitJoinQueueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type JoinQueue401JSONResponse struct{ UnauthorizedJSONResponse }

func (response JoinQueue401JSONResponse) VisitJoinQueueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type JoinQueue404JSONResponse ErrorResponse

func (response JoinQueue404JSONResponse) VisitJoinQueueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type JoinQueue409JSONResponse ErrorResponse

func (response JoinQueue409JSONResponse) VisitJoinQueueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type JoinQueue500JSONResponse struct{ InternalErrorJSONResponse }

func (response JoinQueue500JSONResponse) VisitJoinQueueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetQueuePositionRequestObject struct {
	EventId EventId `json:"eventId"`
}

type GetQueuePositionResponseObject interface {
	VisitGetQueuePositionResponse(w http.ResponseWriter) error
}

type GetQueuePosition200JSONResponse QueuePositionResponse

func (response GetQueuePosition200JSONResponse) VisitGetQueuePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetQueuePosition401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetQueuePosition401JSONResponse) VisitGetQueuePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetQueuePosition404JSONResponse ErrorResponse

func (response GetQueuePosition404JSONResponse) VisitGetQueuePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetQueuePosition500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetQueuePosition500JSONResponse) VisitGetQueuePositionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200JSONResponse HealthResponse

func (response HealthCheck200JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HealthCheck503JSONResponse HealthResponse

func (response HealthCheck503JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type PaystackWebhookRequestObject struct {
	Params PaystackWebhookParams
	Body   *PaystackWebhookJSONRequestBody
}

type PaystackWebhookResponseObject interface {
	VisitPaystackWebhookResponse(w http.ResponseWriter) error
}

type PaystackWebhook200Response struct {
}

func (response PaystackWebhook200Response) VisitPaystackWebhookResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PaystackWebhook400JSONResponse ErrorResponse

func (response PaystackWebhook400JSONResponse) VisitPaystackWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PaystackWebhook500JSONResponse struct{ InternalErrorJSONResponse }

func (response PaystackWebhook500JSONResponse) VisitPaystackWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type QueueWebSocketRequestObject struct {
	EventId EventId `json:"eventId"`
	Params  QueueWebSocketParams
}

type QueueWebSocketResponseObject interface {
	VisitQueueWebSocketResponse(w http.ResponseWriter) error
}

type QueueWebSocket101Response struct {
}

func (response QueueWebSocket101Response) VisitQueueWebSocketResponse(w http.ResponseWriter) error {
	w.WriteHeader(101)
	return nil
}

type QueueWebSocket401JSONResponse struct{ UnauthorizedJSONResponse }

func (response QueueWebSocket401JSONResponse) VisitQueueWebSocketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Request OTP
	// (POST /auth/customer/otp/request)
	RequestOTP(ctx context.Context, request RequestOTPRequestObject) (RequestOTPResponseObject, error)
	// Verify OTP
	// (POST /auth/customer/otp/verify)
	VerifyOTP(ctx context.Context, request VerifyOTPRequestObject) (VerifyOTPResponseObject, error)
	// Organizer login
	// (POST /auth/organizer/login)
	OrganizerLogin(ctx context.Context, request OrganizerLoginRequestObject) (OrganizerLoginResponseObject, error)
	// Release a claim
	// (DELETE /claims/{claimId})
	ReleaseClaim(ctx context.Context, request ReleaseClaimRequestObject) (ReleaseClaimResponseObject, error)
	// Initialize payment
	// (POST /claims/{claimId}/payments)
	InitializePayment(ctx context.Context, request InitializePaymentRequestObject) (InitializePaymentResponseObject, error)
	// Create event
	// (POST /events)
	CreateEvent(ctx context.Context, request CreateEventRequestObject) (CreateEventResponseObject, error)
	// Get event
	// (GET /events/{eventId})
	GetEvent(ctx context.Context, request GetEventRequestObject) (GetEventResponseObject, error)
	// Activate event
	// (PUT /events/{eventId}/activate)
	ActivateEvent(ctx context.Context, request ActivateEventRequestObject) (ActivateEventResponseObject, error)
	// Claim a ticket
	// (POST /events/{eventId}/claims)
	ClaimTicket(ctx context.Context, request ClaimTicketRequestObject) (ClaimTicketResponseObject, error)
	// End event
	// (PUT /events/{eventId}/end)
	EndEvent(ctx context.Context, request EndEventRequestObject) (EndEventResponseObject, error)
	// Abandon queue
	// (DELETE /events/{eventId}/queue)
	AbandonQueue(ctx context.Context, request AbandonQueueRequestObject) (AbandonQueueResponseObject, error)
	// Join queue
	// (POST /events/{eventId}/queue)
	JoinQueue(ctx context.Context, request JoinQueueRequestObject) (JoinQueueResponseObject, error)
	// Get queue position
	// (GET /events/{eventId}/queue/position)
	GetQueuePosition(ctx context.Context, request GetQueuePositionRequestObject) (GetQueuePositionResponseObject, error)
	// Health check
	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// Paystack webhook
	// (POST /webhooks/paystack)
	PaystackWebhook(ctx context.Context, request PaystackWebhookRequestObject) (PaystackWebhookResponseObject, error)
	// Queue position WebSocket
	// (GET /ws/queue/{eventId})
	QueueWebSocket(ctx context.Context, request QueueWebSocketRequestObject) (QueueWebSocketResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RequestOTP operation middleware
func (sh *strictHandler) RequestOTP(w http.ResponseWriter, r *http.Request) {
	var request RequestOTPRequestObject

	var body RequestOTPJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestOTP(ctx, request.(RequestOTPRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestOTP")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestOTPResponseObject); ok {
		if err := validResponse.VisitRequestOTPResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyOTP operation middleware
func (sh *strictHandler) VerifyOTP(w http.ResponseWriter, r *http.Request) {
	var request VerifyOTPRequestObject

	var body VerifyOTPJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyOTP(ctx, request.(VerifyOTPRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyOTP")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyOTPResponseObject); ok {
		if err := validResponse.VisitVerifyOTPResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// OrganizerLogin operation middleware
func (sh *strictHandler) OrganizerLogin(w http.ResponseWriter, r *http.Request) {
	var request OrganizerLoginRequestObject

	var body OrganizerLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OrganizerLogin(ctx, request.(OrganizerLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OrganizerLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OrganizerLoginResponseObject); ok {
		if err := validResponse.VisitOrganizerLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReleaseClaim operation middleware
func (sh *strictHandler) ReleaseClaim(w http.ResponseWriter, r *http.Request, claimId ClaimId) {
	var request ReleaseClaimRequestObject

	request.ClaimId = claimId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReleaseClaim(ctx, request.(ReleaseClaimRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReleaseClaim")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReleaseClaimResponseObject); ok {
		if err := validResponse.VisitReleaseClaimResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InitializePayment operation middleware
func (sh *strictHandler) InitializePayment(w http.ResponseWriter, r *http.Request, claimId ClaimId) {
	var request InitializePaymentRequestObject

	request.ClaimId = claimId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InitializePayment(ctx, request.(InitializePaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InitializePayment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InitializePaymentResponseObject); ok {
		if err := validResponse.VisitInitializePaymentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEvent operation middleware
func (sh *strictHandler) CreateEvent(w http.ResponseWriter, r *http.Request) {
	var request CreateEventRequestObject

	var body CreateEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEvent(ctx, request.(CreateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEventResponseObject); ok {
		if err := validResponse.VisitCreateEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEvent operation middleware
func (sh *strictHandler) GetEvent(w http.ResponseWriter, r *http.Request, eventId EventId) {
	var request GetEventRequestObject

	request.EventId = eventId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEvent(ctx, request.(GetEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEventResponseObject); ok {
		if err := validResponse.VisitGetEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ActivateEvent operation middleware
func (sh *strictHandler) ActivateEvent(w http.ResponseWriter, r *http.Request, eventId EventId) {
	var request ActivateEventRequestObject

	request.EventId = eventId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ActivateEvent(ctx, request.(ActivateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ActivateEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ActivateEventResponseObject); ok {
		if err := validResponse.VisitActivateEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ClaimTicket operation middleware
func (sh *strictHandler) ClaimTicket(w http.ResponseWriter, r *http.Request, eventId EventId) {
	var request ClaimTicketRequestObject

	request.EventId = eventId

	var body ClaimTicketJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ClaimTicket(ctx, request.(ClaimTicketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClaimTicket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ClaimTicketResponseObject); ok {
		if err := validResponse.VisitClaimTicketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EndEvent operation middleware
func (sh *strictHandler) EndEvent(w http.ResponseWriter, r *http.Request, eventId EventId) {
	var request EndEventRequestObject

	request.EventId = eventId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EndEvent(ctx, request.(EndEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EndEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EndEventResponseObject); ok {
		if err := validResponse.VisitEndEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AbandonQueue operation middleware
func (sh *strictHandler) AbandonQueue(w http.ResponseWriter, r *http.Request, eventId EventId) {
	var request AbandonQueueRequestObject

	request.EventId = eventId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AbandonQueue(ctx, request.(AbandonQueueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AbandonQueue")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AbandonQueueResponseObject); ok {
		if err := validResponse.VisitAbandonQueueResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// JoinQueue operation middleware
func (sh *strictHandler) JoinQueue(w http.ResponseWriter, r *http.Request, eventId EventId) {
	var request JoinQueueRequestObject

	request.EventId = eventId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.JoinQueue(ctx, request.(JoinQueueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "JoinQueue")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(JoinQueueResponseObject); ok {
		if err := validResponse.VisitJoinQueueResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetQueuePosition operation middleware
func (sh *strictHandler) GetQueuePosition(w http.ResponseWriter, r *http.Request, eventId EventId) {
	var request GetQueuePositionRequestObject

	request.EventId = eventId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetQueuePosition(ctx, request.(GetQueuePositionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetQueuePosition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetQueuePositionResponseObject); ok {
		if err := validResponse.VisitGetQueuePositionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(w http.ResponseWriter, r *http.Request) {
	var request HealthCheckRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx, request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		if err := validResponse.VisitHealthCheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PaystackWebhook operation middleware
func (sh *strictHandler) PaystackWebhook(w http.ResponseWriter, r *http.Request, params PaystackWebhookParams) {
	var request PaystackWebhookRequestObject

	request.Params = params

	var body PaystackWebhookJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PaystackWebhook(ctx, request.(PaystackWebhookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PaystackWebhook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PaystackWebhookResponseObject); ok {
		if err := validResponse.VisitPaystackWebhookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// QueueWebSocket operation middleware
func (sh *strictHandler) QueueWebSocket(w http.ResponseWriter, r *http.Request, eventId EventId, params QueueWebSocketParams) {
	var request QueueWebSocketRequestObject

	request.EventId = eventId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.QueueWebSocket(ctx, request.(QueueWebSocketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "QueueWebSocket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(QueueWebSocketResponseObject); ok {
		if err := validResponse.VisitQueueWebSocketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
