"""init tables

Revision ID: 2be36c9211ed
Revises:
Create Date: 2026-03-31 02:32:57.682355

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2be36c9211ed'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'events',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('organizer_id', sa.Integer(), nullable=False),
		sa.Column('name', sa.String(), nullable=False),
		sa.Column('total_inventory', sa.Integer(), nullable=False),
		sa.Column('sale_start', sa.DateTime(timezone=True), nullable=False),
		sa.Column('sale_end', sa.DateTime(timezone=True), nullable=False),
		sa.Column(
			'allocation_strategy',
			sa.Enum('FIFO', 'LOTTERY', 'WEIGHTED', name='allocation_strategy'),
			nullable=False,
		),
		sa.Column('price_per_item', sa.Integer(), nullable=False),
		sa.Column(
			'status',
			sa.Enum('ACTIVE', 'UPCOMING', 'ENDED', 'SOLDOUT', name='event_status'),
			nullable=False,
		),
		sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
	op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
	op.create_table(
		'users',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('email', sa.String(), nullable=False),
		sa.Column('name', sa.String(), nullable=False),
		sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
	op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
	op.create_table(
		'inventory_items',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('event_id', sa.Integer(), nullable=False),
		sa.Column('item_type', sa.String(), nullable=False),
		sa.Column('price', sa.Integer(), nullable=False),
		sa.Column(
			'status',
			sa.Enum('AVAILABLE', 'CLAIMED', 'CONFIRMED', 'RELEASED', name='item_status'),
			nullable=False,
		),
		sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
		sa.ForeignKeyConstraint(
			['event_id'],
			['events.id'],
		),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(
		'ix_inventory_available',
		'inventory_items',
		['event_id'],
		unique=False,
		postgresql_where=sa.text("status = 'AVAILABLE'"),
	)
	op.create_index('ix_inventory_event_status', 'inventory_items', ['event_id', 'status'], unique=False)
	op.create_index(op.f('ix_inventory_items_event_id'), 'inventory_items', ['event_id'], unique=False)
	op.create_table(
		'queue_entries',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('event_id', sa.Integer(), nullable=False),
		sa.Column('user_id', sa.Integer(), nullable=False),
		sa.Column('queue_position', sa.Integer(), nullable=False),
		sa.Column(
			'status',
			sa.Enum('WAITING', 'ADMITTED', 'COMPLETED', 'ABANDONED', 'EXPIRED', name='queue_status'),
			nullable=False,
		),
		sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
		sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True),
		sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
		sa.ForeignKeyConstraint(
			['event_id'],
			['events.id'],
		),
		sa.ForeignKeyConstraint(
			['user_id'],
			['users.id'],
		),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(
		'ix_queue_active',
		'queue_entries',
		['event_id', 'queue_position'],
		unique=False,
		postgresql_where=sa.text("status IN ('WAITING', 'ADMITTED')"),
	)
	op.create_index(op.f('ix_queue_entries_event_id'), 'queue_entries', ['event_id'], unique=False)
	op.create_index(op.f('ix_queue_entries_user_id'), 'queue_entries', ['user_id'], unique=False)
	op.create_index(
		'ix_queue_event_status_position',
		'queue_entries',
		['event_id', 'status', 'queue_position'],
		unique=False,
	)
	op.create_table(
		'claims',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('event_id', sa.Integer(), nullable=False),
		sa.Column('item_id', sa.Integer(), nullable=True),
		sa.Column('user_id', sa.Integer(), nullable=False),
		sa.Column(
			'status',
			sa.Enum(
				'CLAIMED', 'PAYMENT_PENDING', 'CONFIRMED', 'RELEASING', 'RELEASED', name='claimstatus'
			),
			nullable=False,
		),
		sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
		sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
		sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
		sa.ForeignKeyConstraint(
			['event_id'],
			['events.id'],
		),
		sa.ForeignKeyConstraint(
			['item_id'],
			['inventory_items.id'],
		),
		sa.ForeignKeyConstraint(
			['user_id'],
			['users.id'],
		),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(
		'ix_claims_active_expiry',
		'claims',
		['expires_at'],
		unique=False,
		postgresql_where=sa.text("status IN ('CLAIMED', 'PAYMENT_PENDING')"),
	)
	op.create_index(op.f('ix_claims_event_id'), 'claims', ['event_id'], unique=False)
	op.create_index('ix_claims_event_status', 'claims', ['event_id', 'status'], unique=False)
	op.create_index(op.f('ix_claims_user_id'), 'claims', ['user_id'], unique=False)
	op.create_index(
		'uq_claims_active_user_event',
		'claims',
		['user_id', 'event_id'],
		unique=True,
		postgresql_where=sa.text("status IN ('CLAIMED', 'PAYMENT_PENDING')"),
	)
	op.create_table(
		'payments',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('claim_id', sa.Integer(), nullable=False),
		sa.Column('payment_reference', sa.String(), nullable=False),
		sa.Column('price', sa.Integer(), nullable=False),
		sa.Column(
			'status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='payment_status'), nullable=False
		),
		sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
		sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
		sa.ForeignKeyConstraint(
			['claim_id'],
			['claims.id'],
		),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(op.f('ix_payments_claim_id'), 'payments', ['claim_id'], unique=False)
	op.create_index(
		op.f('ix_payments_payment_reference'), 'payments', ['payment_reference'], unique=True
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
	op.drop_index(op.f('ix_payments_claim_id'), table_name='payments')
	op.drop_table('payments')
	op.drop_index(
		'uq_claims_active_user_event',
		table_name='claims',
		postgresql_where=sa.text("status IN ('CLAIMED', 'PAYMENT_PENDING')"),
	)
	op.drop_index(op.f('ix_claims_user_id'), table_name='claims')
	op.drop_index('ix_claims_event_status', table_name='claims')
	op.drop_index(op.f('ix_claims_event_id'), table_name='claims')
	op.drop_index(
		'ix_claims_active_expiry',
		table_name='claims',
		postgresql_where=sa.text("status IN ('CLAIMED', 'PAYMENT_PENDING')"),
	)
	op.drop_table('claims')
	op.drop_index('ix_queue_event_status_position', table_name='queue_entries')
	op.drop_index(op.f('ix_queue_entries_user_id'), table_name='queue_entries')
	op.drop_index(op.f('ix_queue_entries_event_id'), table_name='queue_entries')
	op.drop_index(
		'ix_queue_active',
		table_name='queue_entries',
		postgresql_where=sa.text("status IN ('WAITING', 'ADMITTED')"),
	)
	op.drop_table('queue_entries')
	op.drop_index(op.f('ix_inventory_items_event_id'), table_name='inventory_items')
	op.drop_index('ix_inventory_event_status', table_name='inventory_items')
	op.drop_index(
		'ix_inventory_available',
		table_name='inventory_items',
		postgresql_where=sa.text("status = 'AVAILABLE'"),
	)
	op.drop_table('inventory_items')
	op.drop_index(op.f('ix_users_id'), table_name='users')
	op.drop_index(op.f('ix_users_email'), table_name='users')
	op.drop_table('users')
	op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
	op.drop_index(op.f('ix_events_id'), table_name='events')
	op.drop_table('events')
	# ### end Alembic commands ###
