"""added initialization status to payments and made auth_url nullable

Revision ID: 9f05182fc332
Revises: 2be36c9211ed
Create Date: 2026-04-02 03:32:16.256554

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f05182fc332'
down_revision: str | Sequence[str] | None = '2be36c9211ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('payments', sa.Column('authorization_url', sa.String(), nullable=True))
	op.create_index(
		op.f('ix_payments_authorization_url'), 'payments', ['authorization_url'], unique=False
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_payments_authorization_url'), table_name='payments')
	op.drop_column('payments', 'authorization_url')
	# ### end Alembic commands ###
